/* tslint:disable */
/* eslint-disable */
/* prettier-ignore */

/* auto-generated by NAPI-RS */

const {
    existsSync,
    readFileSync
} = require('fs')
const {
    join
} = require('path')

const {
    platform,
    arch
} = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
    // For Node 10
    if (!process.report || typeof process.report.getReport !== 'function') {
        try {
            const lddPath = require('child_process').execSync('which ldd').toString().trim()
            return readFileSync(lddPath, 'utf8').includes('musl')
        } catch (e) {
            return true
        }
    } else {
        const {
            glibcVersionRuntime
        } = process.report.getReport().header
        return !glibcVersionRuntime
    }
}

switch (platform) {
    case 'android':
        switch (arch) {
            case 'arm64':
                localFileExisted = existsSync(join(__dirname, 'zwalker.android-arm64.node'))
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./zwalker.android-arm64.node')
                    } else {
                        nativeBinding = require('zwalker-android-arm64')
                    }
                } catch (e) {
                    loadError = e
                }
                break
            case 'arm':
                localFileExisted = existsSync(join(__dirname, 'zwalker.android-arm-eabi.node'))
                try {
                    if (localFileExisted) {
                        nativeBinding = require('./zwalker.android-arm-eabi.node')
                    } else {
                        nativeBinding = require('zwalker-android-arm-eabi')
                    }
                } catch (e) {
                    loadError = e
                }
                break
            default:
                throw new Error(`Unsupported architecture on Android ${arch}`)
        }
        break
    case 'win32':
        switch (arch) {
            case 'x64':
                try {
                    nativeBinding = require('./win32-x64-msvc/zwalker.win32-x64-msvc.node')
                } catch (e) {
                    loadError = e
                }
                break
            case 'ia32':
                try {
                    nativeBinding = require('./win32-ia32-msvc/zwalker.win32-ia32-msvc.node')
                } catch (e) {
                    loadError = e
                }
                break
            default:
                throw new Error(`Unsupported architecture on Windows: ${arch}`)
        }
        break
    case 'darwin':
        switch (arch) {
            case 'x64':
                try {
                    nativeBinding = require('./darwin-x64/zwalker.darwin-x64.node')
                } catch (e) {
                    loadError = e
                }
                break
            case 'arm64':
                try {
                    nativeBinding = require('./darwin-arm64/zwalker.darwin-arm64.node')
                } catch (e) {
                    loadError = e
                }
                break
            default:
                throw new Error(`Unsupported architecture on macOS: ${arch}`)
        }
        break
    case 'freebsd':
        if (arch !== 'x64') {
            throw new Error(`Unsupported architecture on FreeBSD: ${arch}`)
        }
        localFileExisted = existsSync(join(__dirname, 'zwalker.freebsd-x64.node'))
        try {
            if (localFileExisted) {
                nativeBinding = require('./zwalker.freebsd-x64.node')
            } else {
                nativeBinding = require('zwalker-freebsd-x64')
            }
        } catch (e) {
            loadError = e
        }
        break
    case 'linux':
        // Pure-JS port replicating the NAPI-RS backup-scanner contract
        // (marker .zwalker.json lifecycle, homeless stats) — see ./linux.js
        nativeBinding = require('./linux.js')
        break
    default:
        throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
    if (loadError) {
        throw loadError
    }
    throw new Error(`Failed to load native binding`)
}

const {
    scanDirectory,
    updateReferenceMessageId,
    deleteHomelessFiles,
    statUnmarkedFiles,
    deleteEmptyFolders
} = nativeBinding

module.exports.scanDirectory = scanDirectory;
module.exports.updateReferenceMessageId = updateReferenceMessageId;
module.exports.deleteHomelessFiles = deleteHomelessFiles;
module.exports.statUnmarkedFiles = statUnmarkedFiles;
module.exports.deleteEmptyFolders = deleteEmptyFolders;